version: '3.8'

services:
  telegram-bot:
    build: .
    restart: unless-stopped
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - TOKEN=${TOKEN}
      - BOT_NAME=${BOT_NAME}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PORT=8080
      - WEBHOOK_PATH=/webhook
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
